---
# These settings are synced to GitHub by https://probot.github.io/apps/settings/

_extends: gh-templates:.github/common-settings.yml

repository:
  name: "helm-charts"
  description: "Helm Charts collection"
  homepage: "https://helm-charts.rwxd.eu/"
  topics: "k8s, kubernetes, helm"
